DELETE FROM "AgentDefinition"
WHERE "key" IN (
  'PLANNER_AGENT',
  'IMAGE_ANALYST_AGENT',
  'TEXT_ANALYST_AGENT',
  'BRAND_AGENT',
  'ARTISTIC_BASE_AGENT',
  'PROMPT_ARCHITECT_AGENT',
  'SAFETY_AGENT',
  'QUALITY_AGENT'
);
