/**
 * Image Overlay Service.
 *
 * Composes the texts produced by LAYOUT_OVERLAY_AGENT (memory M-OVERLAY) on
 * top of the raw image generated by GeminiImageProvider. Uses sharp to
 * rasterise an SVG layer over the base PNG. Re-uploads the composed image to
 * the configured storage provider (Cloudinary) and returns the new URL.
 *
 * The agent is expected to emit JSON in the shape:
 *
 *   {
 *     "title":    { "text": "...", "x": "50%", "y": "12%", "fontSize": 72, "color": "#fff", "align": "center", "fontWeight": "bold" },
 *     "subtitle": { ... },
 *     "services": [ { "text": "...", "x": "50%", "y": "45%", ... }, ... ],
 *     "cta":      { "text": "...", "x": "50%", "y": "88%", "background": "#FFA500", "padding": 12, ... }
 *   }
 *
 * x/y can be percentages ("50%") or pixel integers. Any missing field falls
 * back to safe defaults. Unknown fields are ignored — the LAYOUT_OVERLAY
 * agent can freely extend the schema and we'll just render what we know.
 */

import sharp from 'sharp';
import { prisma } from '../../config/database';
import { logger } from '../../utils/logger';
import { getStorageProvider } from '../storage/storage.provider';

const OVERLAY_MEMORY_KEYS = ['M-OVERLAY', 'M_OVERLAY'] as const;

type Align = 'start' | 'middle' | 'end';

interface TextSpec {
  text: string;
  x: string | number;
  y: string | number;
  fontSize: number;
  color: string;
  fontFamily?: string;
  fontWeight?: string;
  align?: Align | 'left' | 'center' | 'right';
  background?: string;
  padding?: number;
  rotation?: number;
}

interface OverlaySpec {
  title?: TextSpec;
  subtitle?: TextSpec;
  services?: TextSpec[];
  cta?: TextSpec;
  extras?: TextSpec[];
}

function asNumber(v: unknown, fallback: number): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

function asString(v: unknown, fallback = ''): string {
  return typeof v === 'string' ? v : fallback;
}

function alignToAnchor(value: TextSpec['align']): Align {
  if (value === 'left' || value === 'start') return 'start';
  if (value === 'right' || value === 'end') return 'end';
  return 'middle';
}

function resolvePosition(value: string | number, dimension: number): number {
  if (typeof value === 'number') return value;
  const str = String(value ?? '').trim();
  if (str.endsWith('%')) {
    const pct = Number(str.slice(0, -1));
    if (Number.isFinite(pct)) return Math.round((pct / 100) * dimension);
  }
  const num = Number(str);
  if (Number.isFinite(num)) return num;
  return Math.round(dimension / 2);
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function normaliseText(input: unknown): TextSpec | null {
  if (!input || typeof input !== 'object') return null;
  const obj = input as Record<string, unknown>;
  const text = asString(obj.text);
  if (!text.trim()) return null;
  return {
    text,
    x: (obj.x as string | number) ?? '50%',
    y: (obj.y as string | number) ?? '50%',
    fontSize: asNumber(obj.fontSize, 32),
    color: asString(obj.color, '#FFFFFF'),
    fontFamily: typeof obj.fontFamily === 'string' ? obj.fontFamily : undefined,
    fontWeight: typeof obj.fontWeight === 'string' ? obj.fontWeight : 'normal',
    align: (obj.align as TextSpec['align']) ?? 'center',
    background: typeof obj.background === 'string' ? obj.background : undefined,
    padding: asNumber(obj.padding, 0),
    rotation: asNumber(obj.rotation, 0),
  };
}

function normaliseOverlay(input: unknown): OverlaySpec | null {
  if (!input || typeof input !== 'object') return null;
  const obj = input as Record<string, unknown>;
  const out: OverlaySpec = {};
  if (obj.title) out.title = normaliseText(obj.title) ?? undefined;
  if (obj.subtitle) out.subtitle = normaliseText(obj.subtitle) ?? undefined;
  if (Array.isArray(obj.services)) {
    out.services = obj.services
      .map(normaliseText)
      .filter((t): t is TextSpec => Boolean(t));
  }
  if (obj.cta) out.cta = normaliseText(obj.cta) ?? undefined;
  if (Array.isArray(obj.extras)) {
    out.extras = obj.extras
      .map(normaliseText)
      .filter((t): t is TextSpec => Boolean(t));
  }
  return out;
}

function renderTextElement(spec: TextSpec, width: number, height: number): string {
  const anchor = alignToAnchor(spec.align);
  const x = resolvePosition(spec.x, width);
  const y = resolvePosition(spec.y, height);
  const ff = spec.fontFamily ? `font-family="${escapeXml(spec.fontFamily)}"` : 'font-family="Inter, Helvetica, Arial, sans-serif"';
  const weight = spec.fontWeight ? `font-weight="${escapeXml(spec.fontWeight)}"` : '';
  const rotate = spec.rotation && spec.rotation !== 0 ? `transform="rotate(${spec.rotation}, ${x}, ${y})"` : '';

  let bgRect = '';
  if (spec.background) {
    // Approximate width via text length × fontSize (good enough for a CTA chip).
    const approxW = spec.text.length * spec.fontSize * 0.6 + (spec.padding ?? 0) * 2;
    const approxH = spec.fontSize * 1.4 + (spec.padding ?? 0) * 2;
    const rectX = anchor === 'middle' ? x - approxW / 2 : anchor === 'end' ? x - approxW : x;
    const rectY = y - approxH * 0.75;
    bgRect = `<rect x="${rectX}" y="${rectY}" width="${approxW}" height="${approxH}" rx="${Math.round(approxH * 0.25)}" fill="${escapeXml(spec.background)}" />`;
  }

  // Soft drop-shadow for readability against any background.
  const shadow = `style="paint-order:stroke;stroke:#000000;stroke-opacity:0.45;stroke-width:${Math.max(2, spec.fontSize * 0.05)}px"`;

  return `${bgRect}<text x="${x}" y="${y}" fill="${escapeXml(spec.color)}" font-size="${spec.fontSize}" ${ff} ${weight} text-anchor="${anchor}" dominant-baseline="middle" ${shadow} ${rotate}>${escapeXml(spec.text)}</text>`;
}

function buildSvg(spec: OverlaySpec, width: number, height: number): string {
  const elements: string[] = [];
  if (spec.title) elements.push(renderTextElement(spec.title, width, height));
  if (spec.subtitle) elements.push(renderTextElement(spec.subtitle, width, height));
  if (spec.services) elements.push(...spec.services.map((s) => renderTextElement(s, width, height)));
  if (spec.cta) elements.push(renderTextElement(spec.cta, width, height));
  if (spec.extras) elements.push(...spec.extras.map((s) => renderTextElement(s, width, height)));
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
${elements.join('\n')}
</svg>`;
}

async function loadOverlaySpec(travailId: string): Promise<OverlaySpec | null> {
  for (const key of OVERLAY_MEMORY_KEYS) {
    const def = await prisma.memoryDefinition.findUnique({ where: { key }, select: { id: true } });
    if (!def) continue;
    const entry = await prisma.memoryEntry.findUnique({
      where: { travailId_memoryDefinitionId: { travailId, memoryDefinitionId: def.id } },
      select: { content: true },
    });
    if (!entry?.content) continue;
    // Accept either { ...spec } directly or { overlay: spec } nested.
    const raw = (entry.content as Record<string, unknown>).overlay ?? entry.content;
    const spec = normaliseOverlay(raw);
    if (spec && (spec.title || spec.subtitle || spec.services?.length || spec.cta || spec.extras?.length)) {
      return spec;
    }
  }
  return null;
}

async function fetchPng(url: string): Promise<Buffer> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch image (${res.status}): ${url}`);
  const arr = await res.arrayBuffer();
  return Buffer.from(arr);
}

/**
 * Compose the overlay (if available) onto the base image URL. Returns a new
 * URL pointing to the composed PNG, or null when no overlay spec exists for
 * the travail (caller keeps the original URL).
 */
export async function composeOverlayForTravail(
  travailId: string,
  baseImageUrl: string,
  variationNumber: number,
): Promise<string | null> {
  let spec: OverlaySpec | null;
  try {
    spec = await loadOverlaySpec(travailId);
  } catch (err) {
    logger.warn('[imageOverlay] failed to load M-OVERLAY', err instanceof Error ? err.message : err);
    return null;
  }
  if (!spec) return null;

  let basePng: Buffer;
  try {
    basePng = await fetchPng(baseImageUrl);
  } catch (err) {
    logger.warn('[imageOverlay] failed to fetch base image', err instanceof Error ? err.message : err);
    return null;
  }

  let width = 0;
  let height = 0;
  try {
    const meta = await sharp(basePng).metadata();
    width = meta.width ?? 1024;
    height = meta.height ?? 1024;
  } catch (err) {
    logger.warn('[imageOverlay] failed to read base image metadata', err instanceof Error ? err.message : err);
    return null;
  }

  const svg = buildSvg(spec, width, height);

  let composed: Buffer;
  try {
    composed = await sharp(basePng)
      .composite([{ input: Buffer.from(svg), top: 0, left: 0 }])
      .png()
      .toBuffer();
  } catch (err) {
    logger.warn('[imageOverlay] sharp composite failed', err instanceof Error ? err.message : err);
    return null;
  }

  try {
    const storage = getStorageProvider();
    const uploaded = await storage.uploadFile({
      buffer: composed,
      originalName: `composed-v${variationNumber}.png`,
      mimetype: 'image/png',
      usageType: 'GENERATED_POSTER',
    });
    return uploaded.fileUrl;
  } catch (err) {
    logger.warn('[imageOverlay] composed upload failed', err instanceof Error ? err.message : err);
    return null;
  }
}
