export {
  createProject,
  deleteProject,
  fetchAgentRuns,
  fetchGeneratedPosters,
  fetchProject,
  fetchProjectFiles,
  fetchProjects,
  generateFinalPrompt,
  generateImages,
  runAgent,
  updateProject,
  uploadProjectFile,
  // Travail-scoped helpers (canonical names + back-compat aliases)
  createTravail,
  deleteTravail,
  fetchTravail,
  fetchTravaux,
  fetchTravailMemories,
  getTravailMemory,
  updateTravail,
  upsertTravailMemory,
  // Back-compat aliases kept so existing UI imports don't break in one pass
  fetchProjectMemories,
  getProjectMemory,
  upsertProjectMemory,
} from "@/lib/projects"
